"""Add job posting

Revision ID: 21f6a5adb97e
Revises: 55f1782163fc
Create Date: 2023-03-13 10:03:53.636295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21f6a5adb97e"
down_revision = "55f1782163fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_posting",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("standard_job_id", sa.String(), nullable=False),
        sa.Column("country_code", sa.String(), nullable=True),
        sa.Column("days_to_hire", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_posting", schema="public")
    # ### end Alembic commands ###
