"""Add standard jobs

Revision ID: 55f1782163fc
Revises: 
Create Date: 2023-03-13 10:02:42.512580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55f1782163fc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "standard_job",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("standard_job_family_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_table(
        "standard_job_family",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("standard_job_family", schema="public")
    op.drop_table("standard_job", schema="public")
    # ### end Alembic commands ###
