"""created task HireStatistic

Revision ID: 6eae2e3188cb
Revises: 991ecb2bf269
Create Date: 2023-04-02 23:28:52.943859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eae2e3188cb'
down_revision = '991ecb2bf269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hire_statistic',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('minimum_days_to_hire', sa.DECIMAL(), nullable=False),
    sa.Column('average_days_to_hire', sa.DECIMAL(), nullable=False),
    sa.Column('maximum_days_to_hire', sa.DECIMAL(), nullable=False),
    sa.Column('job_postings_number', sa.Integer(), nullable=False),
    sa.Column('standard_job_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hire_statistic', schema='public')
    # ### end Alembic commands ###
